### PR TITLE
romanssinicins_pullrequest_1

### PR DESCRIPTION
**Pull request by romanssinicins**
1. code splitted into several files;
2. makefile added;
3. readme file modified.

There is a problem with checkWin. Dont understand, when win diagonally.
Can I try to get with it in next pull request?

best regards,
Romans

### CODE REVIEW

**Comment by GMPrakhar** [comment]
Sure.. why did you close this request though?

Regards,
Prakhar

**Comment by romanssinicins** [comment]
Sorry :) my brains work bad because of that covid :)
request reopened

**Comment by romanssinicins** [comment]
I will append **_checkWin.cpp_** about checking also for diagonally wins.

**Comment by romanssinicins** [comment]
You will confirm this request and I wil try to make another one about that diagonally wining?

best regards,
Romans

**Comment by romanssinicins** [comment]
Hello, Prakhar!

I want to  merge 2 commits into GMPrakhar:master from romanssinicins:master

What do You think about it?

First commit:

1. code splited into several files;
2. makefile added;
3. readme file modified.

Second commit:

1. now correctly check the diagonals;
2. more advanced rand mode;
3. Now the computer is trying to occupy the middle area to increase the probability of winning.

---
Best regards,
Romans Siņicins
+371 20611006
romans@sinicins.com

**Comment by GMPrakhar** [comment]
PR looks good.. I have merged it.

**Comment by romanssinicins** [comment]
I am glad i could help.

I will try to check, what happens, when it draw.


/b.r., R.S.

**Pull request merged**
